// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cisgtbibblwmcbewkefp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpc2d0YmliYmx3bWNiZXdrZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTc1NDEsImV4cCI6MjA2NTU3MzU0MX0.nnS9D7snyrHu39mVEiK3t26oy9DhrpekfR9gJEbiUOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});